### ISSUE TITLE
elocrypt-0.3.1 can't compile its test suite

### ISSUE THREAD

**Issue by peti** [sgillespie/elocrypt#2]
Citing from http://hydra.cryp.to/build/853000/nixlog/2/raw:

~~~~~~~~~~~
Preprocessing test suite 'test' for elocrypt-0.3.1...

test/Tests.hs:6:18:
    Could not find module ‘Test.ElocryptTest’
    Use -v to see a list of the files searched for.

test/Tests.hs:7:18:
    Could not find module ‘Test.Elocrypt.TrigraphTest’
    Use -v to see a list of the files searched for.
~~~~~~~~~~~

**Comment by sgillespie** [comment]
How exactly is this being built?  I can't find a way to reproduce that failure

**Comment by peti** [comment]
Download the release archive from Hackage and compile that one. It's missing those modules mentioned above.

**Comment by sgillespie** [comment]
Potential fix: http://hackage.haskell.org/package/elocrypt-0.3.2/candidate

**Comment by peti** [comment]
Yes, the new version compiles fine.

**Comment by sgillespie** [comment]
Fixed here:  http://hackage.haskell.org/package/elocrypt-0.3.2
